[project]
name = "encrypt-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "cryptography>=46.0.3",
    "pymongo[srv]>=4.15.3",
    "python-dotenv>=1.1.1",
]
